/**
 * FETCH THE CONNECTOR LOGOS ONCE, AND COMMIT WHAT CAME BACK.
 *
 * Generates `src/connectors/logos.ts` from Simple Icons. Run by hand when a
 * connector is added or a brand redraws its mark:
 *
 *   node scripts/fetch-logos.mjs
 *
 * ═══ WHY THE PATHS ARE COMMITTED RATHER THAN FETCHED ═══
 *
 * The app's CSP allows no external images, and a logo that arrives over the
 * network is a logo that is missing on a slow connection and a request that
 * tells a third party who is looking at your dashboard. Ten path strings cost
 * about 11KB in the bundle and render instantly, offline, forever.
 *
 * Committing them also makes the provenance auditable: the mark in the repo is
 * the mark that was reviewed, and a brand changing theirs is a diff somebody
 * reads rather than a silent swap.
 *
 * ═══ WHAT IS DELIBERATELY NOT HERE ═══
 *
 * SIXTEEN CONNECTORS ARE NOT ON SIMPLE ICONS AT ALL — Close, Pipedrive,
 * Klaviyo, Attio, Tally, lemlist, JustCall, Thinkific, Customer.io, Smartlead,
 * Whop, Instantly, SavvyCal, OnceHub, ThriveCart, Retell. Probed directly
 * against the CDN across three versions and several slug spellings; they are
 * not published. Those keep the initials tile until somebody supplies an SVG.
 *
 * AND `fathom` IS EXCLUDED ON PURPOSE. Simple Icons carries a "Fathom" icon,
 * but it belongs to Fathom ANALYTICS — a different company from the Fathom
 * notetaker this connector talks to. Shipping it would put the wrong
 * company's mark on a customer's integration, which is worse than two letters.
 *
 * `webhook` keeps its tile too: it is not a brand, it is a category.
 *
 * ═══ LICENSING ═══
 *
 * Simple Icons publishes the icon files under CC0-1.0, so redistribution is
 * unencumbered. The MARKS remain the trademarks of their owners; using them to
 * identify which integration a row is about is nominative use, which is the
 * one thing trademark law is clearest about. That is also why nothing here
 * recolours or redraws them beyond the monochrome glyph the set ships.
 */
import { writeFileSync } from "node:fs";

/**
 * `source` → Simple Icons slug. Written out rather than derived: `gsheets` is
 * `googlesheets` and `calcom` is `caldotcom`, and a guessed slug that happens
 * to resolve is how the wrong company's logo ships.
 */
const SLUGS = {
  calendly: "calendly",
  gsheets: "googlesheets",
  gcal: "googlecalendar",
  stripe: "stripe",
  aircall: "aircall",
  helpscout: "helpscout",
  paddle: "paddle",
  airtable: "airtable",
  mailchimp: "mailchimp",
  shopify: "shopify",
};

/**
 * PUBLISHED, FETCHED, LOOKED AT, AND LEFT OUT: Cal.com, Typeform and
 * WooCommerce.
 *
 * All three ship a WORDMARK rather than a symbol — the company's name set in
 * type, inside the 24×24 box. Rendered at the sizes this product actually uses
 * they are unreadable: at `SourceMark`'s 20px default each is a grey smudge,
 * and even the apps grid's 40px only makes them small text.
 *
 * Two clear letters beat an illegible logo, which is the same judgement
 * `brandNeedsDarkInk` already encodes one file over — a mark nobody can read is
 * worse than no mark. They keep their tiles until somebody supplies the
 * symbol-only version each of these brands also publishes.
 *
 * Measured, not assumed: rendered at 20px and 40px and compared against the ten
 * that stayed.
 */
const WORDMARKS_NOT_USED = ["calcom", "typeform", "woocommerce"];

const VERSION = "15";
const out = {};
const titles = {};

for (const [source, slug] of Object.entries(SLUGS)) {
  const res = await fetch(`https://cdn.jsdelivr.net/npm/simple-icons@${VERSION}/icons/${slug}.svg`);
  if (!res.ok) {
    console.error(`  ! ${source}: ${slug} returned HTTP ${res.status} — skipped`);
    continue;
  }
  const svg = await res.text();
  const d = svg.match(/ d="([^"]+)"/)?.[1];
  const title = svg.match(/<title>([^<]*)<\/title>/)?.[1] ?? slug;
  if (!d) {
    console.error(`  ! ${source}: no path found in ${slug}.svg — skipped`);
    continue;
  }
  /**
   * Every Simple Icons glyph is a single path on a 24×24 viewBox. Asserting it
   * here means a set that ever changes shape fails the generator rather than
   * rendering as a smear at one thirtieth scale.
   */
  if (!svg.includes('viewBox="0 0 24 24"')) {
    console.error(`  ! ${source}: ${slug} is not on a 24×24 viewBox — skipped`);
    continue;
  }
  out[source] = d;
  titles[source] = title;
  console.log(`  ✓ ${source.padEnd(12)} ${slug.padEnd(16)} "${title}"  ${d.length} chars`);
}

const body = `/**
 * GENERATED by \`node scripts/fetch-logos.mjs\` — do not edit by hand.
 *
 * One SVG path per connector, from Simple Icons (CC0-1.0), each on a 24×24
 * viewBox and drawn in \`currentColor\` so the tile's own ink rule decides
 * whether it is white or near-black.
 *
 * A connector absent from this map keeps the two-letter tile, which is the
 * fallback for every brand Simple Icons does not publish — and for \`fathom\`,
 * whose entry there belongs to a different company. See the generator's header.
 *
 * ${Object.keys(out).length} of the catalogue's connectors have a mark here.
 */
export const SOURCE_LOGOS: Readonly<Record<string, string>> = Object.freeze({
${Object.entries(out)
  .map(([k, v]) => `  // ${titles[k]}\n  ${k}: ${JSON.stringify(v)},`)
  .join("\n")}
});
`;

writeFileSync("src/connectors/logos.ts", body);
console.log(`\nWrote src/connectors/logos.ts — ${Object.keys(out).length} logo(s).`);
console.log(
  `Skipped as wordmarks (illegible at 20px, see above): ${WORDMARKS_NOT_USED.join(", ")}.\n` +
    `Everything else in the catalogue keeps its two-letter tile.`,
);
